# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.3
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix  ]
      - id: ruff-format

-   repo: https://github.com/henriquegemignani/jsonschema-to-typeddict
    rev: v1.3
    hooks:
    -   id: jsonschema-to-typeddict
        files: src/mars_patcher/data/schema.json
        args: [ --output-path, src/mars_patcher/auto_generated_types.py, --root-name, MarsSchema ]
